title: "My GitHub Page"
description: "Welcome to my personal website!"
theme: minima
author: "Wang Han"
email: "w-h23@mails.tsinghua.edu.cn"
timezone: "Asia/Beijing"
collections:
  posts:
    output: true
